# Generated by Django 4.2.5 on 2023-09-25 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_notes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
