# Generated by Django 4.2.5 on 2023-09-25 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_notes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 0, 59, 2, 364257, tzinfo=datetime.timezone.utc)),
        ),
    ]
