# Generated by Django 4.2.5 on 2023-09-25 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_notes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 1, 0, 26, 591814, tzinfo=datetime.timezone.utc)),
        ),
    ]
