# Generated by Django 4.2.5 on 2023-09-25 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_notes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
